name: Next.js Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v21.4.0
      uses: actions/setup-node@v3
      with:
        node-version: '21.4.0'
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: '8.15.4'
    - run: pnpm i
    - run: pnpm build
